### ISSUE TITLE
Localizado error que impide la creación de la tabla del plugin

### ISSUE THREAD

**Issue by tonioruiz** [kungfuclass/kfc-form-autoevaluacion-terepebernal#1]
Hola, @terepebernal:

En la línea 45 del fichero **kfp_form_autoevaluacion.php** había un pequeño bug que provocaba un error de SQL al ejecutar la consulta.
Donde dice:
```
created at datetime NOT NULL,
```
debe decir: 
```
created_at datetime NOT NULL,
```

Lo he localizado con el viejo truco (aunque no muy ortodoxo) de hacer un 
```
echo $query;
exit();
```

Por cierto que en las líneas 33 y 35 hay un espacio sobrante entre el objeto $wpdb y la flecha que apunta a la función aunque eso parece no causar ningún problema (ni siquiera lo canta el PHP Code Sniffer que tengo en el Visual Studio Code con lo cascarrabias que es)

Bueno ya me contarás, y si lo solucionas pon esta incidencia como resuelta

**Comment by perezbernalmt** [comment]
Todo arreglado. Muchas gracias.
