### ISSUE TITLE
Quiero cambiar el último commit - Ayuda por favor - 

### ISSUE THREAD

**Issue by perezbernalmt** [kungfuclass/kfc-form-autoevaluacion-terepebernal#2]
Como hacía algún tiempo que no trabajaba en el plugin, no me he dado cuenta que había creado una rama para añadir los niveles que faltaban.
Como este último commit va sobre otro tema me gustaría quitarlo de aquí y crear otra rama distinta. Quitarlo de aquí y también en local, claro.
Una pregunta: Si consigo corregirlo en local y luego hago un push para actualizar el repositorio remoto,  ¿se cambiaría todo aquí (en remoto) tal cual lo tengo en local, sin tocar nada (aquí en remoto)?
No sé si me explico :). 
Gracias

**Comment by perezbernalmt** [comment]
He conseguido arreglarlo, aunque un poco a lo bruto. Lo explico en el diario. Cierro incidencia.

**Comment by tonioruiz** [comment]
Siento no haber llegado a tiempo para ayudarte, aunque veo que al final lo has arreglado. En principio los cambios del repositorio local se reflejan en el remoto y viceversa.
